baseURL = "https://thirsty-allen-2bc611.netlify.app"
languageCode = "en-us"
title = "Movie Soundtracks"
author = "Roger & Anthony"
theme = "SoundtrackDark"
paginate= 3
[outputs]
  home = ["HTML", "JSON"]